# Generated by Django 3.2.3 on 2021-05-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210514_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default='articles/default_avatar.png', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
