# Generated by Django 3.2.3 on 2021-05-19 11:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210514_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
